name: Reusable Semgrep CE Scan

on:
  workflow_call:

jobs:
  semgrep:
    name: semgrep-oss/scan
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      contents: read
    container:
      image: semgrep/semgrep
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Semgrep CE
        run: semgrep scan --config auto
